#!/usr/bin/env python3
"""Export HTML/CSS/JS files as C/C++ raw string literals or PROGMEM byte arrays for ESP32 / Arduino / C / C++ HTTP servers."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def minify_css(css: str) -> str:
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.DOTALL)
    css = re.sub(r"\s+", " ", css)
    css = re.sub(r"\s*([:;{}])\s*", r"\1", css)
    return css.strip()


def minify_html(html: str) -> str:
    html = re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)
    html = re.sub(r">\s+<", "><", html)
    html = re.sub(r"\s+", " ", html)
    return html.strip()


def minify_js(js: str) -> str:
    js = re.sub(r"/\*.*?\*/", "", js, flags=re.DOTALL)
    js = re.sub(r"//.*?\n", "", js)
    js = re.sub(r"\s+", " ", js)
    return js.strip()


def generate_c_header(html_path: Path | None, css_path: Path | None, js_path: Path | None, output_path: Path) -> None:
    lines = [
        "/* ==========================================================================",
        " * Auto-generated Web UI Assets Header for Embedded C/C++ Web Servers",
        " * Generated by Tung Lam Web UI Export Tool",
        " * ========================================================================== */",
        "",
        "#pragma once",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
    ]

    if css_path and css_path.exists():
        raw_css = minify_css(css_path.read_text(encoding="utf-8"))
        lines.extend([
            "/* Minified CSS Asset */",
            f'static const char UI_CSS[] = R"rawliteral({raw_css})rawliteral";',
            f"static const unsigned int UI_CSS_LEN = {len(raw_css.encode('utf-8'))}U;",
            "",
        ])

    if js_path and js_path.exists():
        raw_js = minify_js(js_path.read_text(encoding="utf-8"))
        lines.extend([
            "/* Minified JS Asset */",
            f'static const char UI_JS[] = R"rawliteral({raw_js})rawliteral";',
            f"static const unsigned int UI_JS_LEN = {len(raw_js.encode('utf-8'))}U;",
            "",
        ])

    if html_path and html_path.exists():
        raw_html = minify_html(html_path.read_text(encoding="utf-8"))
        lines.extend([
            "/* Minified HTML Asset */",
            f'static const char UI_HTML[] = R"rawliteral({raw_html})rawliteral";',
            f"static const unsigned int UI_HTML_LEN = {len(raw_html.encode('utf-8'))}U;",
            "",
        ])

    lines.extend([
        "#ifdef __cplusplus",
        "}",
        "#endif",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated C/C++ Web Assets Header at: {output_path}")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--html", type=Path, help="Path to input HTML file")
    parser.add_argument("--css", type=Path, help="Path to input CSS file")
    parser.add_argument("--js", type=Path, help="Path to input JS file")
    parser.add_argument("--output", "-o", type=Path, default=Path("ui_assets.h"),
                        help="Target output .h file path.")
    args = parser.parse_args(argv)

    if not any([args.html, args.css, args.js]):
        parser.error("At least one of --html, --css, or --js must be provided.")

    try:
        generate_c_header(args.html, args.css, args.js, args.output)
        return 0
    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
